---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/gosec --version
    register: gosec_test_output
  - name: gosec --version
    debug:
      msg: '{{ gosec_test_output.stdout }}'
