---
- name: Testing andrewrothstein.gosec
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'gosec --version'
      ansible.builtin.command: gosec --version
      changed_when: false
      register: gosec_test_output
    - name: Output from 'gosec --version'
      ansible.builtin.debug:
        msg: '{{ gosec_test_output.stdout }}'
