---
# tasks file for ansible-gosec
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for existing install in {{ gosec_install_dir }}
  become: '{{ gosec_privilege_escalate }}'
  become_user: root
  changed_when: false
  ansible.builtin.stat:
    path: '{{ gosec_install_dir }}'
  register: gosec_binary
- name: Downloading and installing gosec
  when: not gosec_binary.stat.exists
  block:
    - name: Downloading {{ gosec_url }}
      become: '{{ gosec_privilege_escalate }}'
      become_user: root
      ansible.builtin.get_url:
        url: '{{ gosec_url }}'
        checksum: '{{ gosec_checksum }}'
        dest: '{{ gosec_tmp_archive }}'
        mode: '644'
    - name: Mkdir {{ gosec_install_dir }}
      become: '{{ gosec_privilege_escalate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ gosec_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ gosec_tmp_archive }} to {{ gosec_install_dir }}
      become: '{{ gosec_privilege_escalate }}'
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ gosec_tmp_archive }}'
        dest: '{{ gosec_install_dir }}'
        creates: '{{ gosec_install_exe }}'
  always:
    - name: Rm -f {{ gosec_tmp_archive }}
      become: '{{ gosec_privilege_escalate }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ gosec_tmp_archive }}'
        state: absent
- name: Link gosec and gosec-{{ gosec_ver }}
  become: '{{ gosec_privilege_escalate }}'
  become_user: root
  with_items:
    - '{{ gosec_link }}'
    - '{{ gosec_ver_link }}'
  ansible.builtin.file:
    src: '{{ gosec_install_exe }}'
    dest: '{{ item }}'
    state: link
